# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tD5c7ay3lQ-0lrU5tdDIwMRlekjzCgiS
"""

import streamlit as st
from transformers import pipeline

@st.cache_resource
def load_model():
    ner_pipeline = pipeline(
        "ner",
        model="./NER",
        tokenizer="./NER",
        aggregation_strategy="simple"
    )
    return ner_pipeline

ner = load_model()

st.set_page_config(page_title="Named Entity Recognition App", layout="centered")

st.title("Named Entity Recognition")
st.write("Enter text and identify entities like PERSON, ORG, LOCATION.")

text_input = st.text_area("Enter your text here:", height=150)


if st.button("Recognize Entities"):
    if text_input.strip() == "":
        st.warning("Please enter some text")
    else:
        results = ner(text_input)

        if len(results) == 0:
            st.info("No entities found.")
        else:
            st.subheader(" Detected Entities")

            for entity in results:
                word = entity["word"]
                label = entity["entity_group"]
                score = entity["score"]

                st.markdown(
                    f"**{word}** → `{label}`  \nConfidence: `{score:.2f}`"
                )
